package lab09_04_08.parser;

public enum TokenType { // important: SKIP, IDENT, and NUM must have ordinals 1, 2 and 3 
	EOF, SKIP, IDENT, NUM, STRING, PRINT, LET, PLUS, TIMES, EQ, ASSIGN, OPEN_PAR,
	CLOSE_PAR, OPEN_PAIR, CLOSE_PAIR, STMT_SEP, EXP_SEP, OPEN_BLOCK, CLOSE_BLOCK_OR_SET, MINUS, NOT, AND, BOOL,
	IF, ELSE, FST, SND, IN, WHILE, CONCAT, INTERSECT, UNION, LENGTH,

}
